name: Deploy to S3 and Cloudfront

on:
  push:
    branches:
      - main

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Add node.js
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Installing Dependencies
        run: npm install

      # Build
      - name: Build react app
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_ACCESS_KEY_SECRET: ${{secrets. AWS_ACCESS_KEY_SECRET}}
          AWS_REGION: ${{secrets.AWS_REGION}}
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_S3_BUCKET }} --delete --region $AWS_REGION

      - name: Clear Cloudfront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_ACCESS_KEY_SECRET: ${{secrets. AWS_ACCESS_KEY_SECRET}}
          AWS_REGION: ${{secrets.AWS_REGION}}
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DIST_ID }} --paths "/*" --region $AWS_REGION